name: gomarketme
description: Affiliate Marketing for Flutter-Based iOS and Android Apps.
version: 5.0.2
homepage: https://gomarketme.co
repository: https://github.com/GoMarketMe/gomarketme-flutter

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.24.0"

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: GomarketmeFlutterPlugin
      android:
        package: co.gomarketme.flutter
        pluginClass: GomarketmeFlutterPlugin

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
